### ISSUE TITLE
missing qb data and dup obs

### ISSUE THREAD

**Issue by AngusHewitt** [nflverse/espnscrapeR-data#2]
espn_Qbr_rating_21 <- load_espn_qbr("nfl", 2021, "weekly")

# WAS qb data missing week 1, 2021
# david mills dups obs week 7, 2021, likely other dups

**Comment by mpcen** [comment]
Bumbing this to get visibility. Looks like 2023, week 2 has 30 duplicated QB's with slighly different QBR numbers

**Comment by mrcaseb** [comment]
WAS week 1, 2021 is missing in the source https://www.espn.com/nfl/qbr/_/view/weekly/season/2021/seasontype/2/week/1

Assuming neither Heinicke nor Fitzpatrick met the 20 plays requirement

**Comment by mrcaseb** [comment]
Dups fixed in #4
